version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
      - "5565:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5445/pollstream
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pollstream
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5445:5432"
volumes:
  pgdata: